# Add CI specific values here
########################################
## CONFIG | Configuration Store Configs
## See aiSSEMBLE aissemble-configuration-store-chart: README for more details.
## https://github.com/boozallen/aissemble/
########################################

aissemble-configuration-store-chart:
  aissemble-quarkus-chart:
    deployment:
      image:
        imagePullPolicy: IfNotPresent
    service:
      type: LoadBalancer

  configurationVolume:
    storageType: "local"
    volumePathOnNode: "/Users/csun/bah/tests/src/main/resources/configurations"
